#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:
    external:
      name: volt_ordering_network

services:
  cliMagnetoCorp:
    container_name: cliVoltLogistics
    image: hyperledger/fabric-tools:2.0.0-beta
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.voltlogistics.vltenterprise.com:9051
      - CORE_PEER_LOCALMSPID=VoltLogisticsMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/voltlogistics.vltenterprise.com/users/Admin@voltlogistics.vltenterprise.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/voltlogistics.vltenterprise.com/peers/peer0.voltlogistics.vltenterprise.com/tls/ca.crt
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/vltenterprise.com/orderers/orderer.vltenterprise.com/msp/tlscacerts/tlsca.vltenterprise.com-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./../../../../organization/voltlogistics:/opt/gopath/src/github.com/
        - ./../../../../../VoltOrderingNetwork/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - ordering
